### PR TITLE
restore gdal test

### PR DESCRIPTION
**Pull request by ocefpaf**
This will fail for now, sending it so we don't forget it later. We should restart this once https://github.com/conda-forge/gdal-feedstock/pull/377 is merged

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@ocefpaf would you be interested in opening an issue against cf-scripts? We might be able to break these kinds of cycles if we make some heuristics, for instance eliminating the bad edges if they come from test. Also we might be able to only open PRs if any member of the cycle is on the buildable frontier

**Comment by ocefpaf** [comment]
> @ocefpaf would you be interested in opening an issue against cf-scripts? We might be able to break these kinds of cycles if we make some heuristics, for instance eliminating the bad edges if they come from test. Also we might be able to only open PRs if any member of the cycle is on the buildable frontier

Makes sense but this is a cycle where we will always have to intervene, no?
`gdal` depends on `kealib` and `kealib` tests depend on `gdal`. Only by disabling the tests we can build it.

I guess that, ideally, we could have an "allow failures" test section (conda-build feature request wink, wink) and ignore test dependencies on the graph. What do you think? The latter is something that we could do now and let the PR fail regardless. The former is a bit harder to implement.

**Comment by CJ-Wright** [comment]
I think we should exclude tests only when we have to.

**Comment by ocefpaf** [comment]
> I think we should exclude tests only when we have to.

Well. I meant within the context here, so yes. Only when needed :smile:

**Comment by gillins** [comment]
Thanks for working through this. I'm happy to disable the test for now as this is going to be a problem each time we re-pin `hdf5`...

**Comment by ocefpaf** [comment]
> Thanks for working through this. I'm happy to disable the test for now as this is going to be a problem each time we re-pin `hdf5`...

It is fine to have cycles like that as long as we are OK doing this manual change. At least until we have a way to represent a "allow failures" test and inform the bot to ignore the cycle in the test case.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
