### PR TITLE
Patch kea config.in

### PR DESCRIPTION
**Pull request by ocefpaf**
Need in https://github.com/conda-forge/gdal-feedstock/pull/293

### CODE REVIEW

**Comment by gillins** [comment]
Thanks @ocefpaf. I'll do a PR for `kealib` 1.4.11

**Comment by ocefpaf** [comment]
> Thanks @ocefpaf. I'll do a PR for `kealib` 1.4.11

Thanks! I should've checked for the new release instead of patching.

**Comment by gillins** [comment]
Actually, let's not bother. Your patch already captures the only meaningful change between the versions. I'll wait until the next release before upgrading - unless you disagree.

**Comment by ocefpaf** [comment]
> Actually, let's not bother. Your patch already captures the only meaningful change between the versions. I'll wait until the next release before upgrading - unless you disagree.

Sounds good to me :smile:

**Pull request merged**
